// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import "context"

// Querier is the interface that wraps all generated query methods.
// It enables mocking in tests and supports dependency injection.
type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, id int32) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	DeleteUser(ctx context.Context, id int32) error
	CountUsers(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
